#baseURL = 'https://sskagemo.github.io/skagemo.no/'
baseURL = 'https://skagemo.no/'
languageCode = 'no'
title = 'S. Skagemo, forvaltningsinformatiker og elsykkelevangelist'
theme = 'hugo-flex'

[permalinks]
    blog = "/blog/:year/:month/:slug" 