#baseURL = 'https://sskagemo.github.io/skagemo.no/'
baseURL = 'https://skagemo.no/'
languageCode = 'no'
title = 'S. Skagemo, forvaltningsinformatiker og elsykkelevangelist'
theme = 'simplecss'

[permalinks]
    blog = "/blog/:year/:month/:slug" 