baseURL = 'https://skagemo.no/'
languageCode = 'no-nb'
title = 'forvaltningsinformatiker Steinar Skagemo'
theme = 'hugo-flex'

[params]
    color = "#156A15"
    footer = """<em>Forvaltningsinformatiker Steinar Skagemo</em> i Brønnøysundregistrene: <a href="https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=982909392">982 909 392</a>"""
    rss = "For å abonnere, kopier adressen til denne nettsiden og lim den inn i din foretrukne RSS-leser"
    linkicons = true
    schema = true
    summaries = true


[permalinks]
    blog = "/blog/:year/:month/:slug" 

[[menu.nav]]
name = "Om"
url = "om"
weight = 1

[[menu.nav]]
name = "Blogg"
url = "blog/"
weight = 2

[[menu.nav]]
name = "Tema"
url = "tags/"
weight = 3

#[[menu.nav]]
#name = "Categories"
#url = "categories/"
#weight = 4

[[menu.nav]]
name = "RSS"
url = "index.xml"
weight = 5

